use objc2_app_kit::{NSPasteboard, NSWorkspace};
use objc2_foundation::NSString;

/// Pasteboard type markers that mean "do not record this".
///
/// These are the nspasteboard.org conventions that password managers (1Password,
/// Bitwarden, KeePassXC, …) set on copied secrets. Honoring them is the difference
/// between a clipboard history and a password dump.
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

const HTML_TYPE: &str = "public.html";
const RTF_TYPE: &str = "public.rtf";

/// Monotonic counter bumped by the OS on every pasteboard write.
///
/// Reading this is a single integer fetch — it does not take ownership of the
/// pasteboard, allocate, or touch the payload. That is what makes a 250ms poll
/// effectively free, versus reading the contents on a timer.
pub fn sequence() -> i64 {
    NSPasteboard::generalPasteboard().changeCount() as i64
}

fn pasteboard_has_type(name: &str) -> bool {
    let pasteboard = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return false;
    };
    let needle = NSString::from_str(name);
    types.iter().any(|t| *t == *needle)
}

pub fn is_concealed() -> bool {
    CONCEALED_TYPES.iter().any(|t| pasteboard_has_type(t))
}

pub fn has_html() -> bool {
    pasteboard_has_type(HTML_TYPE)
}

pub fn has_rtf() -> bool {
    pasteboard_has_type(RTF_TYPE)
}

/// Name of the app that currently owns the keyboard, used as the clip's source.
///
/// Best-effort: this is read after the copy has already happened, so a very fast
/// app switch can attribute a clip to the wrong app. It is a label, never a
/// security control — the blocklist check it feeds is a convenience, and the
/// authoritative "don't record this" signal is `is_concealed`.
pub fn frontmost_app() -> Option<String> {
    let workspace = NSWorkspace::sharedWorkspace();
    let app = workspace.frontmostApplication()?;
    app.localizedName().map(|n| n.to_string())
}
